[project]
name = "claude-git"
version = "0.1.0"
description = "Create a git worktree that tracks claude-code changes without polluting the main repo's git history"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "claude-saga>=0.1.0",
]
